### ISSUE TITLE
Oirearvio 22: Kysymykset eivät näy

### ISSUE THREAD

**Issue by kainutom** [omahoito/rfc#101]
Kysymysten enableWhen ehto viittaa kysymykseen 584, jota ei ole olemassa. Tämä estää kysymysten näyttämisen.

**Comment by Tomkinen** [comment]
VKT:n käyttöliittymässä näkyy oikein. Tutkin miksi fhir exporttiin tulee väärin. Palaan asiaan.

**Comment by Tomkinen** [comment]
VKT:n käyttöliittymässä näkyy oikein. Tutkin miksi fhir exporttiin tulee väärin. Palaan asiaan.

**Comment by Tomkinen** [comment]
Tämä on nyt korjattu fhir export generointi -koodiin. Pitää vielä siirtää tuotantoon ja sen jälkeen lomake pitää julkaista uudestaan.

**Comment by Tomkinen** [comment]
Tuotantoon siirto tehty. Lomake julkaistu. Onko nyt ok?

**Comment by kainutom** [comment]
Tämä ok @jarinumminen

**Comment by jarinumminen** [comment]
suljetaan
