### ISSUE TITLE
Oirearviot 83 & 107: Kysymys itsehoitoarviosta puuttuu

### ISSUE THREAD

**Issue by kainutom** [omahoito/rfc#102]
Muissa arvioissa on tämä kysymys alussa:
![image](https://user-images.githubusercontent.com/22096314/30050309-b564a0da-9226-11e7-9cf6-21e361548d2b.png)

Onko tarkoitus että olisi näin kaikissa?

**Comment by Wildarts** [comment]
107 kyselyssä muistaakseni päädytiin siihen, että ei tarjota alkuun tätä vaihtoehtoa. Voin lisätä sen sijaan valinnan kyselyyn 83.

**Comment by Wildarts** [comment]
Ongelma taisi kyselyssä 83 olla se, ettei siitä ole oikein sopivaa itsehoito-ohjeistusta olemassa.
