### ISSUE TITLE
Oirearviot antaa "Failsafe" ilmoituksen jos vastaa vain haluavansa itsehoitoa

### ISSUE THREAD

**Issue by kainutom** [omahoito/rfc#104]
Valitset näin:
![image](https://user-images.githubusercontent.com/22096314/30056636-21b87512-923c-11e7-91b9-be91277f3172.png)

Saat vastauksen:
![image](https://user-images.githubusercontent.com/22096314/30056669-40814c4e-923c-11e7-9c83-17f98ac22d02.png)

Eikö tässä kuuluisi kytkeä palautteeksi itsehoito-ohje?

**Comment by Wildarts** [comment]
Näissä tapauksissa on ajateltu, että palaute tulee suoraan käyttöliittymästä, kuten myös yllä olevassa kuvassa näkyy. Käyttöliittymässä tulisi siis näissä tapauksissa estää varsinaisen kyselysanoman lähettäminen. Vaihtoehtoisesti voimme koodata jokaiseen kyselyyn ja niistä vastaavaan skriptiin täysin saman sisältöisen palautteen, mutta tämä vaatinee aika paljon aikaa ja testausta.

**Comment by kainutom** [comment]
Lomakkeesta ei voida päätellä millään tavoin milloin lähetys tulisi estää

**Comment by Wildarts** [comment]
Logiikka tulisi tehdä niin, että kun käyttäjä saa suoran palautteen, ei voisi saada enää palautetta rajapinnan kautta. Tämän pitäisi päteä kaikkiin kyselyihin, paitsi hengitystieoireet, johon haluttiin erikseen kaksivaiheinen rakenne. Eli poikkeuskin löytyy.

Joka tapauksessa olisi hieman outoa, että muissa tilanteissa käyttäjä voisi saada sekä suoran palautteen, että rajapinnan kautta tulevan, mahdollisesti erillaisen palautteen.

**Comment by kainutom** [comment]
Näin varmaankin, mutta siis lomakkeessa ei ole mitään minkä perusteella näitä asioita voidaan päätellä. Joten jos tällaisiä halutaan rakentaa niin "logiikka-astukset" tulisi olla lomakepohjassa ja tietysti ohjeet niiden tulkintaan tulisi olla saatavilla ja tiedossa.

**Comment by Wildarts** [comment]
Tämä tulisi speksata yhdessä. Laitan tiedoksi Tomi:lle.

**Comment by jarinumminen** [comment]
Käydään tämä läpi torstain tapaamisessa, kirjaan agendaan

**Comment by JohannesLyytikka** [comment]
Tästä asiasta käytiin keskustelua tänään perjantaina aamun kokouksessa mm. Tomin, Tommin ja Jarin kanssa. Keskustelun päätteeksi toivottiin, että kaikki palautteet siirrettäisiin pois ODA2-käyttöliittymästä ja ne sisällytettäisiin ODA1 tietäymyskannan päättelyskripteihin. Näin saataisiin haluttujen toiminnallisuuksien ja MDD:n kannalta selkeämpi toteutus. 

Tässä ehdotuksessa on muutamia ongelmia, jotka tekevät sen toteuttamisesta epäkäytännöllistä:

- Alunperin välipalaute haluttiin toteuttaa nykyisellä tavalla, jotta käyttäjä saisi kriittisistä oireista tarvittavan ohjeistuksen heti ja riippumatta siitä, onko hänellä sillä hetkellä yhteys EBMeDS palvelimelle. 

- Jotta välipalaute voitaisiin toteuttaa EBMeDS moottorin kautta, tulisi ODA2-käyttöliittymän lähettää kyselysanoma, aina kun käyttäjä muuttaa mitä tahansa kenttää. **Tämä nostaisi kyselsanomien määrää monikymmenkertaiseksi, mikä puolestaan lisäisi serverin kuormaa samassa suhteessa**. Käyttöliittymään tulisi myös viive, jonka käyttäjä todennäköisesti kokisi häiritsevänä.

- Ehdotettu muutos tarkoittaisin kaikkien lomakkeiden ja niitä vastaavien skriptien muuttamista ja uudelleen testaamista. **Tämä vaatisi huomattavan määrän työtä.**  

-------

**Vaihtoehtoinen tapa ratkaista yllä kuvattu ongelma, olisi jatkaa nykyisen välipalautteen käyttöä ja lisätä VKT:n ominaisuuksiin vielä yksi vaihtoehto "lopullinen palaute".** Tämä toimisi kuten välipalaute, mutta estäisi käyttäjää lähettämästä sen jälkeen kyselysanomaa (inaktivoisi tai poistaisi lähetä napin) ja siten saamasta muuta palautetta EBMeDS palvelimelta. Tämän toteuttaminen vaatisi suhteellisen pienen muutoksen VKT:hen ja vastaavan lisäyksen ODA2-käyttöliittymään sekä joidenkin kyselyiden välipalautteiden muuttamisen lopullisiksi palautteiksi. 

Nykyinen välipalaute ja toteutettavaksi ehdotettu loppupalaute ovat käytännössä saman näyttölogiikan sovelluksia, mitä kaikissa kyseyissä muutenkin tullaan käyttämään. **MDD:n kannalta tämä on aivan samalla tavalla Duodecim:in tuottamaa sisältöä, joka vain näytetään muussa käyttöliittymässä.**

**Comment by Tomkinen** [comment]
Hyvä kommentti Johannes. Olen täysin samaa mieltä. Tiedoksi... Lisätty tiketti aiheesta ODA1 jiraan. Mahdollisuus lisätä "lopullinen palaute" -tieto VKT tietokantaan, käyttöliittymään ja FHIR exporttiin ODA2:lle. Toteutetaan jossain sprintissä jos tämä Johanneksen kirjoittama teksti pysyy speksinä.

**Comment by JohannesLyytikka** [comment]
Jos lopullisen palautteen mukana halutaan välittää myös Activity Definition -tieto, voitaneen tämä myös lisätä uudeksi kentäksi.

**Comment by jarinumminen** [comment]
ODA2:n kannalta pitäytyminen yhdessä prosessissa kaikkien lomakkeiden osalta olisi parempi. Eli välipalaute kuten nyt ja mahdollisuus painaa Valmis eli lähettää tiedot päätöksentuelle, joka antaa toimintosuositukset (ActivityDefinitionit). Pointtina se, että ei tarvitse rakentaa erillistä logiikkaa ja koodia lomakkeelta poimittaville ActivityDefinitioneille JA päätöksentuelta voi tulla muita huomioita asiakkaan datasta. Jos se vaihe jätetään pois, niin silloin jää pois muun päätöksentuen palautteen saaminen.

**Comment by JohannesLyytikka** [comment]
Lopullinen palaute-valinta tarvitaan joka tapauksessa tilanteisiin, joissa kysely yksiselitteisesti päättyy eli käyttäjä valitsee itsehoito-ohjeen täyttämättä mitään, syöttää iäksi liian pienen arvon tai ohjataan heti päivystykseen. Näissä tilanteissa ei liene tarvetta konsultoida EBMeDS moottoria?

**Comment by JohannesLyytikka** [comment]
Mietimme tätä asiaa vielä yhdessä päätöksentuen tiimin kanssa ja ehdottaisimme seuraavaa: välipalaute toteutetaan kuten nytkin ja tämän lisäksi tulisi nykyisen toteutuksen variaatio "loppupalaute", jonka erona on ainoastaan se ettei sen jälkeen voi enää lähettää tietoja päätöksentuelle. Kummassakaan ei olisi ActivityDefinition:ia eli nämä tulisivat ainoastaan päätöksentuelta. Näin tarvittaisiin mahdollisimman vähän muutoksia ja kuitenkin katettaisiin kaikki tarpeet. Tässä vielä eri vaihtoiset palautetavat:
- 1. Vain muistute + (AD) 
- 2. Välipalaute ja muistute + (AD)
- 3. Vain loppupalaute
- 4. Välipalaute + loppupalaute 

Tilanteessa jossa käyttäjä ohjataan esim. loppupalautteella päivystykseen, ei voisi siis lähettää AD:tä. Tuolloin pitäisi käyttää välipalaute + muistute + AD kombinaatiota. 

Onko tämä @jarinumminen mielestäsi sopiva ratkaisu?

**Comment by JohannesLyytikka** [comment]
Lähtökohtaisesti lienee myös syytä ohjata käyttäjä aina täyttämään oirekysely kokonaisuudessaan ennen sen lähettämistä päätöksentuelle. Kaikki tulkintalogiikat on rakennettu niin, että niissä oletetaan käyttäjän vastanneen kaikkiin pakolliseksi merkittyihin kysymyksiin. Jos sallitaan puoliksi täytettyjen lomakkeiden lähetys, on näiden tulkintaa käytännössä mahdotonta tehdä luotettavasti. 

Eli itseasiassa toteutus pitäisi tehdä niin, että lähetä nappi on lähtökohtaisesti inaktiivinen ja se aktivoituu vain kuin kaikkiin pakollisiin kysymyksiin on vastattu. Näin toteutettuna loppupalaute-valintaa ei välttämättä edes tarvita.

**Comment by kainutom** [comment]
Pakolliset on täytettävä ODA2 päässä.
Siitä huolimatta vastaanottavan rajapinnan ei pidä ottaa vastaan dataa mitä se ei pysty käsittelemään.

**Comment by JohannesLyytikka** [comment]
Eli tehdään tuplavarmistus? ODA2 päässä estetään tietojen lähettäminen, jos pakollisiin kysymyksiin ei ole vastattu ja ODA1 päässä varmistetaan ettei lähetetty tieto ole keskeneräiseltä lomakkeelta?

**Comment by jarinumminen** [comment]
Loppupalaute on kolmas tapa tuottaa toimintasuosituksia ja siten tuo ylimääräisen liikkuvan osan. Tulevaisuudessa (kun Kanta-tietoja voidaan käyttää kansalaispalveluissa) sanomiin liitetään mukaan asiakkaan muita tietoja (diagnoosit, labrat, lääkkeet jne) ja tämä ei ole mahdollista loppupalautteen kanssa. Siksi parempi tapa olisi:

- Välipalaute kriittisissä tilanteissa tai jos pelkkä itsehoito riittää

- Päätöksentuen palaute aina, jos käyttäjä tekee kyselyn loppuun tai itsehoito-ohjeiden jälkeen klikkaa Valmis/Lähetä. Näin saadaan tuotettua AcitivityDefinition ja siten muodostettua suunnitelma. Tällöin itsehoito-ohjeetkin jäävät asiakkaan suunnitelmalle ja ovat myöhemmin käytettävissä.

Pakollisuudet määritetään Questionnairessa ja siten hallitaan mihin on pakko vastata ennen lähetystä.

**Comment by kainutom** [comment]
"Eli tehdään tuplavarmistus? ODA2 päässä estetään tietojen lähettäminen, jos pakollisiin kysymyksiin ei ole vastattu ja ODA1 päässä varmistetaan ettei lähetetty tieto ole keskeneräiseltä lomakkeelta?"

En ota kantaa mitä tässä tapauksessa rajapinnan "takana" tapahtuu tai mitä se hyväksyy. Yleisesti on huono käytäntö luottaa sokeasti toisen järjestelmän tuottamaan dataan ja jättää validoimatta datan oikeellisuus.  Mutta siis kuten yllä todettu, tässä pakollisuudet tarkistetaan "client" osapuolen toimesta Questionnairen perusteella.

**Comment by JohannesLyytikka** [comment]
@Tomkinen olisiko kyselysanoman validointi paras tehdä moottorissa vaiko yksittäisissä skripteissä?  Eli pitäisi tarkistaa jokaisen kysymyksen kohdalla, että jos kysymyksen visibility = 1 JA pakollisuus = true JA vastaus on tyhjä -> indikoidaan tämä jotenkin. Ehkä tällä hetkellä paras tapa olisi antaa käyttäjälle yleinen palaute, jossa pyydetään vastaamaan kaikkiin kysymyksiin. 

ODA2 päässä tulisi myös pyrkiä siihen, että kyselysanomaa ei voisi lähettää ilman että käyttäjä on vastannut kaikkiin näkyvissä oleviin ja pakollisiin kysymyksiin.

**Comment by jarinumminen** [comment]
Sovittu 28.9.: Jos haluaa vain itsehoitoa, niin päätöksentuelta saa saman ohjeistuksen ja voi ODAssa tallentaa sen omaan suunnitelmaan.

**Comment by Tomkinen** [comment]
Kun fhir questionnaire type='display', niin _type.extension voi saada valuestringiksi "subtitle", "feedback" ja nyt uutuutena myös "terminus".

"subtitle" = väliotsikko
"feedback" = pikapalaute (käyttäjä voi jatkaa lomakkeen täyttämistä)
"terminus" = lopullinen palaute. Käyttäjä ei voi enää jatkaa lomakkeen täyttämistä.

..tämä tulee ottaa huomioon oda2 päässä ja toteuttaa vastaava UI ja toimintalogiikka.

**Comment by Tomkinen** [comment]
Loppupalaute tulee tässä tapauksessa moottorista. Tämä tiketti voidaan sulkea.
