### ISSUE TITLE
Oirearvio 2: Palautteet eivät toimi

### ISSUE THREAD

**Issue by kainutom** [omahoito/rfc#106]
Palautteet eivät näytä toimivan, ei tule vastausta. Tarvittaessa voidaan toimittaa kysely

**Comment by tlehto** [comment]
Moottorissa tai editorissa on ongelma, jota ollaan selvittelemässä.

**Comment by vlindhol** [comment]
Kysely olisi jees.

**Comment by kainutom** [comment]
Näyttäisi ettei anna mitään palautteita millään vastauksilla, sama taitaa toistua VKT:ssa.

**Comment by JohannesLyytikka** [comment]
Nyt toimii, moottorin ongelmien takia skripti oli otettu alkuviikosta pois päältä. Ilmeisesti siirtyminen suoraan javascrip-tilasta published-tilaan ei kompiloi koodia ollenkaan, joten kyseinen skripti oli tyhjä.
