### ISSUE TITLE
Oirearvio 124: Vastausvaihtoehto "ei" puuttuu?

### ISSUE THREAD

**Issue by kainutom** [omahoito/rfc#107]
Kysymykseen "Pahenevatko oireesi seuraavissa tilanteissa?" on pakko vastata myöntävästi:
![image](https://user-images.githubusercontent.com/22096314/30059196-c6852d92-9246-11e7-8b54-1e220aa0aca9.png)

**Comment by Wildarts** [comment]
Lisätty vaihtoehto "Ei mikään yllä olevista"

**Comment by tlehto** [comment]
Tehtiinkö "Ei mikään yllä olevista" -vaihtoehdosta jo päätös muuttaa se toiseen muotoon, esim. "Ei mikään mainituista"

**Comment by Wildarts** [comment]
Tästä keskusteltiin, mutta ei taidettu päättää. Voin pyytää Tomia muuttamaan kaikissa tekstin tuohon muotoon.
