### ISSUE TITLE
Terveystarkastus 153: Kolesteroliarvot pakollisia

### ISSUE THREAD

**Issue by kainutom** [omahoito/rfc#108]
Kolesteriarvot ovat pakollisia vaikka kysymysteksti muuta väittääkin..

![image](https://user-images.githubusercontent.com/22096314/30096774-fdb4d62c-92e2-11e7-9181-dd106fd9aff9.png)

**Comment by tlehto** [comment]
Totta, tsekataan.

**Comment by tlehto** [comment]
VKT:ssa valinnaiseksi on asetettu kaikki teksti ja tekstikenttä -tyyppiset kysymykset. Jos on numeerinen kysymys, niin se on automaattisesti pakollinen.

Numeerisen kysymyksen pakollisuuden määrittäminen VKT:ssa vaatii uuden ominaisuuden lisäämisen. @Tomkinen

**Comment by Tomkinen** [comment]
Lisätty uusi kenttä kantaan, muokattu rajapinnat ja käyttöliittymä. FHIR export päivitetty. Viety tuotantoon. Lomake tulee julkaista uudestaan.

**Comment by Tomkinen** [comment]
Lomake julkaistu. Testatkaa ja sulkekaa tiketti jos kaikki kunnossa. Kävin jo tarkistamassa että näiden kysymysten osalta required:true on poistunut.

**Comment by kainutom** [comment]
Tämä ok @jarinumminen

**Comment by jarinumminen** [comment]
suljetaan
