### ISSUE TITLE
Terveystarkastus 153: Verenpainearvot pakollisia

### ISSUE THREAD

**Issue by kainutom** [omahoito/rfc#109]
Verenpainearvot pakollisia vaikka tekstissä kerrotaan että ne voi jättää tyhjäksi.

![image](https://user-images.githubusercontent.com/22096314/30096895-8299c758-92e3-11e7-81fa-ecefb52c2321.png)

**Comment by tlehto** [comment]
Sama kuin kolesteroli, tsekataan.

**Comment by tlehto** [comment]
VKT:ssa valinnaiseksi on asetettu kaikki teksti ja tekstikenttä -tyyppiset kysymykset. Jos on numeerinen kysymys, niin se on automaattisesti pakollinen.

Numeerisen kysymyksen pakollisuuden määrittäminen VKT:ssa vaatii uuden ominaisuuden lisäämisen. @Tomkinen

**Comment by Tomkinen** [comment]
Lisätty uusi kenttä kantaan, muokattu rajapinnat ja käyttöliittymä. Lisätty checkbox "Kysymykseen vastaaminen ei ole pakollista." FHIR export päivitetty. Viety tuotantoon. Lomake tulee julkaista uudestaan.

**Comment by Tomkinen** [comment]
Lomake julkaistu. Testatkaa ja sulkekaa tiketti jos kaikki kunnossa. Kävin jo tarkistamassa että näiden kysymysten osalta required:true puuttuu.

**Comment by kainutom** [comment]
Tämä ok @jarinumminen

**Comment by jarinumminen** [comment]
suljetaan
