### ISSUE TITLE
Terveystarkastus 153: Otsikko tai seliteteksti puuttuu liikunnan määristä

### ISSUE THREAD

**Issue by kainutom** [omahoito/rfc#110]
Voiko "10-60min" / "Yli tunnin viikossa" valintaryhmälle lisätä otsikon? Käyttäjä hahmottaisi selkeämmin että se on eri vaihtoehtoryhmä kuin yllä oleva.

![image](https://user-images.githubusercontent.com/22096314/30097296-97a98276-92e5-11e7-8b3f-ad3d87efcf80.png)

**Comment by tlehto** [comment]
Hyvä huomio, pitäisi olla mahdollista.

**Comment by tlehto** [comment]
Testasin otsikon lisäämistä VKT:ssa ja näyttäisi toimivan, mutta julkaistaan lomake vasta useampien muutosten jälkeen.
