### ISSUE TITLE
Oirearvio 22: "Oireiden kesto" 

### ISSUE THREAD

**Issue by kainutom** [omahoito/rfc#112]
"Oireiden kesto" viittaa yllä kysyttyyn nenän sivuonteloiden paineoireisiin.
Voisiko tätä tarkentaa tuossa kysymystekstissä/asettelussa? 
- esim. muuttamalla tekstiksi esim. "Paineoireiden kesto" tms.
tai
- niputtamalla koko homman yhdeksi kysymykseksi jossa kolme vastausvaihtoehtoa: Ei, Alle viikon, Yli viikon"

![image](https://user-images.githubusercontent.com/22096314/30107610-f0cfdcca-9307-11e7-9707-bfaf18ae4a71.png)

**Comment by tlehto** [comment]
Palaute huomioitu, mietitään kumpi tapa parempi. Johannes ottanee kantaa tähän.

**Comment by JohannesLyytikka** [comment]
Muutettu tarkentava kysymys muotoon: "Kuinka pitkään paineoireet ovat kestäneet?"
