### ISSUE TITLE
Terveystarkastus: sisällöllisiä huomioita palautteessa

### ISSUE THREAD

**Issue by jarinumminen** [omahoito/rfc#113]
[STAR-tekstit.pdf](https://github.com/omahoito/rfc/files/1283528/STAR-tekstit.pdf)
Ohessa esimerkki, jossa ainakin kaksi huomioitavaa asiaa:
* kappaleita alkaa kesken lauseen
* BMI on esitetty 10 desimaalilla
* kappaleiden sisällä lauseiden välistä puuttuu välilyöntejä tai kappaleiden väliltä puuttuu rivinvaihdot.

**Comment by tlehto** [comment]
Kiitos havainnoista, otetaan heti käsittelyyn!

**Comment by tlehto** [comment]
Jarin liittämän pdf:n mukaan palautteen järjestys on omituinen, epälooginen. Palautteiden järjestys määräytyy ODA1-päässä.

**Comment by vlindhol** [comment]
Jes, se järjestysvika on jo korjattu, mutta korjaus ei ole viety oda-testiin vielä. Yritin täyttää ODA2:n STAR-lomakkeen itse mutta lomake loppui kesken eikä mitään lähetys-nappulaa löytynyt.

**Comment by tlehto** [comment]
@vlindhol Sain ainakin äsken täytettyä: https://oda.medidemo.fi/omaarvio/113

**Comment by kainutom** [comment]
BMI on nyt yhdellä desimaalilla eli lienee ok.

**Comment by kainutom** [comment]
Luetelmaviivat ei näy oikein:
![image](https://user-images.githubusercontent.com/22096314/30322538-79d658b4-97c2-11e7-978e-9f76de1a583c.png)

**Comment by jokimaki** [comment]
Kuulostaa markdown-muunnoksen ongelmalta. Tarkastettava onko vika sisään tulevassa datassa vai ODA2:n markdown->html -muunnoksessa.

**Comment by vlindhol** [comment]
Mitä nyt olen katsonut niin pitäisi rivinvaihdot olla kunnossa sekä alkuperäisessä XML-formaatissamme että ActivityDefinitioneissa. Tosin XML->JSON-konversio tuo turhia välilyöntejä kappaleen alkuun. Jos XML:ssä on

```xml
<RecommendationText>
          <![CDATA[Päivittäinen tupakointisi aiheuttaa keuhkojen ahtautumista ja sydän- ja verisuonisairauksia sekä lisää syövän riskiä. Lisäksi se herkistää ... ]]>
```

Niin xml2js tekee RecommendationText-sisällöstä `"\n          Päivittäinen..."`. Eipä näyttäisi tuottavan ongelmia teille, mutta sanokaa jos tuottaa.

Assignaan nyt @jokimaki kun näyttäisi olevan vika ODA2:n päässä.

**Comment by jokimaki** [comment]
Yksikkötestillä kokeiltuna listan pitäisi muodostua ODA2-päässä, kunhan *-merkkiä edeltää rivinvaihto. Millä syötteillä saa listoja sisältävän palautteen, niin testataan vielä koko putki?

**Comment by vlindhol** [comment]
STARin palaute on nyt päivitetty niin, että koko STAR-raportti tulee yhtenä muistutteena. Rivinvaihtojen pitäisi olla kunnossa FHIRissä vieläkin. Kaivan jonkun sanoman millä voi testata.

**Comment by vlindhol** [comment]
ActivityDefinitionin topic.text-kenttä ei muuten varmaan ole koskaan käsitelty markdownina ODA2:ssa? Muistutteet ovat tyypillisesti puhdasta tekstiä, ainoa markuppi tähän asti on ollut tyyliin linkkejä.

**Comment by jokimaki** [comment]
ActivityDefinitionista käsitellään tällä hetkellä vain description ja code.display. Eli topic.text käsiteltävä myös?

**Comment by jokimaki** [comment]
Topic.text markdown-käsittely toteutettu testiympäristöön. Palautan tämän @vlindhol vielä sinulle: Kolesteroli-otsikko on h1, pitäisi kaiketi olla h2 kuten muutkin.

**Comment by vlindhol** [comment]
Jees! Tosiaan tämä STAR on vähän erikoistapaus kun tulee niin paljon feedbackia joka ei sopinut olemassaolevaan muistutemuotoon, hyvä että markdown pelittää. Tällä näyttäisi toimivan. Korjaan sen otsikon vielä juu.

**Comment by jarinumminen** [comment]
Korjattu
