### ISSUE TITLE
Terveystarkastus 153: Nainen saa palautteen "Vyötärölihavuuden raja on miehillä ..."

### ISSUE THREAD

**Issue by kainutom** [omahoito/rfc#114]
Terveystarkastuksessa valittu sukupuoleksi nainen ja ympärysmitaksi 125.

![image](https://user-images.githubusercontent.com/22096314/30148539-8bc3ab40-93ac-11e7-8535-4ab955ce6f74.png)

**Comment by jarinumminen** [comment]
Toinen esimerkki, jossa nainen täyttänyt: 
Kolesteroliarvosi ovat verisuonisairauksien riskin kannalta hyvällä tasolla, mikäli myös LDL-kolesteroliarvosi on suositelluissa rajoissa, eli ei ylitä arvoa 3 mmol/l.
Et juuri osallistu toimintoihin, joita tehdään yhdessä. Voi olla, että tämä järjestely sopii sinulle. Jos osallistumistasi estää jokin seikka, sinun kannattaa miettiä, olisiko se poistettavissa tai kierrettävissä.
Lue lisää Diabetes
Terveyteen vaikuttavien elintapojesi puolesta kuulut *miehiin*, jotka kuluttavat terveyttään jonkin verran muita enemmän ja siksi sairastuvat keskimääräistä useammin elintapojen aiheuttamiin sairauksiin. Haluat kuitenkin pitää huolta terveydestäsi ja olet ehkä jo yrittänytkin tehdä muutoksia arkisiin tottumuksiisi. Alla on tarkemmin kuvattu, missä asioissa voit edelleen yrittää tehdä muutoksia hyvinvointisi ja terveytesi parantamiseksi.
Tämä voi johtaa siihen, että kiinnostus omaa terveyttä edistävään ravitsemukseen ja liikuntaan on vähäisempää kuin muillaRyhmään kuuluvilla on myös tavallista useammin ongelmia ihmissuhteissa.Voimavarojasi onneksi kartuttaa:* tyytyväisyys saavutuksiisi elämässä* luottamuksesi tulevaisuuteen* halusi elää tässä hetkessä* kiitollisuuden tunteesi.Jos haluat edelleen vahvistaa voimavarojasi ja hyvän elämän edellytyksiäsi, sinulle on hyötyä henkisen hyvinvoinnin harjoitusohjelmista.
on terve luottamus tulevaisuuteen, jaTähän ryhmään kuuluvilla on myös keskimääräistä harvemmin ongelmia sosiaalisissa suhteissa ja parisuhteessa.

**Comment by JohannesLyytikka** [comment]
Tämän voisi ohjata Eetu:lle, joka on koodannut STAR-skriptit. Koodi näyttäisi kyllä ottavan sukupuolen huomioon, mutta jostakin syystä naiset saavat myös miesten muistutteet. Liittynee siihen miten tieto sukupuolesta välittyy tai miten sitä koodissa käsitellään.

**Comment by batati** [comment]
Moro! Oli pieni virhe tuossa vastauksen lukemisessa. Nyt korjattu skripteihin.

**Comment by kainutom** [comment]
Edelleen naiselle: "Vyötärölihavuus eli liikakilojen kertyminen vyötärön seutuun lisää sairauksien vaaraa. Vyötärölihavuuden raja on miehillä 100 cm, ihanteellinen vyötärönympärys on alle 94 cm. Mitään hyppäystä sairauksien vaarassa ei näissä arvoissa tapahdu. Vyötärön ympärys 101 cm ei ole paljon haitallisempi kuin 99 cm. Mitä enemmän 100 cm ylittyy, sitä suurempi vaara on sairauksien kehittymiseen. Vyötärönmittasi on turvallisella alueella. Sen perusteella vaara sairauksiin ei ole lisääntynyt, vaikka painoindeksin perusteella olet lievästi ylipainoinen."

Ja edelleen naiselle myös tämä:
"Elintavat ja -olosuhteet vaikuttavat merkittävästi elinikään. Tilastojen mukaan sinun ikäryhmääsi kuuluvat ja elintavoiltaan samanlaiset miehet saavuttavat keskimäärin 61 vuoden eliniän. Jos muuttaisit kaikki elintapasi mahdollisimman terveellisiksi, sinulla olisi mahdollisuus lisätä vireitä elinvuosiasi 22 vuodella. Alla oleva kuva esittää keskimääräisen ennusteen elinvuosistasi sekä terveellisemmillä elintavoilla saavutettavissa olevista lisävuosista. Sairaat elinvuodet kuvaavat keskimääräistä elämänkaaren loppupäähän sijoittuvaa aikaa, jota sävyttää elämänlaatua heikentävät pitkäaikaissairaudet. Elinikäarviossa on otettu huomioon kaikki antamasi vastaukset. Sen sijaan alempana olevaan sairausriskiarvioon vaikuttavat vain elintapojasi koskevat vastaukset."

**Comment by JohannesLyytikka** [comment]
Saatko Eetu korjattua myös nuo yllä kuvatut ongelmat? @batati

**Comment by vlindhol** [comment]
Pingaan taas @batati, tästä on myös JIRA-taski.

**Comment by batati** [comment]
Korjattu jo silloin, kun viimeksi tänne kommentoin. Ilmeisesti oli vielä vanhat skriptit käytössä sen jälkeen. Tällä hetkellä näyttäisi toimivan medidemossakin.

**Comment by vlindhol** [comment]
Hyvä, suljen tän sitten.
