### ISSUE TITLE
Terveystarkastus 153: STAR-lomakkeen jatkokysymys jää näkyviin

### ISSUE THREAD

**Issue by kainutom** [omahoito/rfc#120]
1) Avaa STAR
2) Vastaa "Haluatko arvioida kuntotasoasi?" vaihtoehto Kyllä
3) Vastaa jatkokysymykseen "Valitse seuraavista vaihtoehdoista, mikä parhaiten kuvaa yleistä aktiivisuuden tasoasi edellisen kuukauden aikana." vaihtoehto "HARRASTAN SÄÄNNÖLLISTÄ VAPAA-AJAN LIIKUNTAA TAI TEEN TÖITÄ, JOTKA VAATIVAT KOHTUULLISTA FYYSISTÄ PONNISTELUA, ESIM. GOLF, RATSASTUS, VOIMISTELU, PÖYTÄTENNIS, KEILAILU, KUNTOSALIHARJOITTELU TAI PUUTARHATYÖT."
4) Avautuu otsikoton jatkokysymys
5) Vaihda vastausta "Haluatko arvioida kuntotasoasi?" eli vastaa siihen Ei
6) Kohdan 4 otsikoton jatkokysymys jää näkyviin

**Comment by tlehto** [comment]
Kiitos, selvitellään

**Comment by tlehto** [comment]
Näyttölogiikka korjattu ja lomake julkaistu. VKThamster APP [2:44 PM] VKT oirekysely "STAR", lomake id: 153, versio id: 458 julkaistu

**Comment by kainutom** [comment]
Tämä ok @jarinumminen

**Comment by jarinumminen** [comment]
suljetaan.
