### ISSUE TITLE
"Tämä kenttä on pakollinen" aktivoituu tarpeettomasti. 

### ISSUE THREAD

**Issue by JohannesLyytikka** [omahoito/rfc#124]
SPT-kyselyssä (ID 42) seksityyppi kysymys (ID 1066) antaa ODA2-käyttöliittymässä aina ilmoituksen että kysymys on pakollinen, riippumatta mitä siihen vastaa.

<img width="1249" alt="nayttokuva 2017-10-18 kello 11 10 22" src="https://user-images.githubusercontent.com/31692452/31709755-9f19cf02-b3fb-11e7-929e-458ea1cc20fe.png">

**Comment by Tomkinen** [comment]
En löydä FHIR questionnairesta ongelmia mitkä selittäisi tämän. Pitäisi tutkia ODA2 päässä mistä kiikastaa. Hence, assign to Tommi. Heitä tiketti minulle takaisin jos on tarvetta jollekin questionnaire FHIR muutokselle.

**Comment by kainutom** [comment]
Päivitetty uusi versio. Ongelma ei ilmeisesti enää toistu?
