### ISSUE TITLE
Lisää text QuestionnaireResponse -resurssiin.

### ISSUE THREAD

**Issue by jaakkokorhonen** [omahoito/rfc#26]
Käytetään Snomed CT koodituksen ihmisluettavia nimiä "text" kentässä.

**Comment by jarinumminen** [comment]
Tähän tarvitaan vielä sisällölliset varmistukset, että hengitystien oirearviossa on nämä merkittynä. Pitää sisällään sekä koodit niiltä osin kun käytettävissä (esim. Kuumeen FinLoinc) ja SNOMED englanninkielisen termin.

**Comment by vlindhol** [comment]
Onko tämä nyt oikeasti lakimiehen kanssa vahvistettu juridinen fakta että me voidaan käyttää Snomedin termistöä ilman lisenssiä?

Nopean googlaamiseen jälkeen näyttäisi siltä että kysymys on melko kompleksinen (http://project.eurotermbank.com/uploads/D2.2%20Standard%20document%20templates%20and%20procedures.pdf sivut 7-8) mutta jos lakimies sen on OK:annut niin mikäs siinä.

**Comment by jarinumminen** [comment]
Voidaan käyttää samoja tekstimuotoisia termejä, mutta ei koodeja. Näin valmistudumme tilanteeseen, jossa käytössä on lisenssi ja voimme aloittaa SNOMEDin käytön. Asia on työn alla THL:ssä.

**Comment by vlindhol** [comment]
Questionnaire-resurssissa on nyt ekstensio joka voi esiintyä joko itemin yhteydessä (`Questionnaire.item.extension`) ja monivalintakysymyksen optionin yhteydessä (`Questionnaire.item.option.extension`). Ekstension kentänarvot ovat `"url": "https://duodecim.fi/fhir/extensions/symptom-checker-other-code-name"` ja `"valueString": "koodi"` missä koodi on jokin Snomedin selkokielinen koodi. QuestionnaireResponseen sen samaisen koodin voi laittaa text-kenttään jos sen haluaa tallentaa sinnekin.

Ja itse asiassa se URL muuttunee vielä hieman, siitä tulee `.../fhir/stu3/...` jotta ei synny sekaannuksia versioiden välillä. Tämä pätee meidän muihinkin profiileihin ym missä käytetään duodecim.fi/fhir-urlia. Sanon tämän Slackissakin.

Nämä ekstensiot eivät näy vielä missään koska snomed-arvoja ei ole täytetty. Sisältöpuolelta halusivatkin tietää mikä näiden arvojen kirjaamisen prioriteetti on pilotteihin nähden, sekä mikäli oikeasti jokaiselle kysymykselle täytyy löytyä jokin koodi. Muistan että tästä keskusteltiin silloin kun tämä issue luotiin mutta siitä on jo aikaa, joten en osannut vastata :) @jarinumminen osaa varmaan kommentoida, joko tähän tai sitten suoraan Ilkalle jolle tämä nakki joka tapauksessa lankeaa.

**Comment by jarinumminen** [comment]
sama asia #47 , suljetaan tämä
