### ISSUE TITLE
Pohjaesitys tavasta kommentoida tietomalli.

### ISSUE THREAD

**Issue by jaakkokorhonen** [omahoito/rfc#29]

**Comment by gellati** [comment]
RFC-repon tietomallit ovat XML-muotoisia. <a href="https://fhir.furore.com/forge/">Forge</a> on työkalu jonka avulla FHIR-profiileja voi luoda ja kommentoida. Siitä näkee myös tietomallin rakenteen.

Forge antaa mahdollisuuden keskittyä mallintamisen toiminnalliseen puoleen ilman että joutuu kosketuksiin FHIR-mallien XML-tiedostojen kompleksisuuden kanssa. Forge myös validoi profiilit automaattisesti.

Forge on ladattavissa <a href="https://fhir.furore.com/forge/">täältä</a>. Ohjelma toimii vain Windowsissa. Sillä voi tehdä ainoastaan XML-muotoisia profiileja.

Forge-ohjelmassa profiilien kenttiä ja elementtejä voi kommentoida "Comments"-osiossa tai "Reason for inclusion and constrainment"-osiossa (Rfiac). Comments-osioon voi laittaa tietoelementtiin liittyviä selittäviä kommentteja ja soveltamisohjeita, ja miten oikealla tavalla käyttää elementtiä. Rfiac-osiossa voi laittaa tietoja siitä miksi elementti luotiin ja miksi siihen liittyviä rajoitteita on tehty, ja laittaa lähteitä näiden perusteluiksi.

**Comment by jaakkokorhonen** [comment]
Tarkennatko @gellati tänne ja suljetko tehtävän? https://github.com/omahoito/rfc/blob/master/README.md

**Comment by gellati** [comment]
Tehty: https://github.com/omahoito/rfc#commenting-the-data-schemas
