### ISSUE TITLE
EHDOTA hoitosuositusten mukana suositeltavat palvelukoodit

### ISSUE THREAD

**Issue by jaakkokorhonen** [omahoito/rfc#31]
Merkitse projektinhallintaan tarvittavat koodit http://koodistopalvelu.kanta.fi/codeserver/pages/publication-view-page.xhtml?distributionKey=8189 pohjalta.

**Comment by jarinumminen** [comment]
Koodit merkitty A-sarakkeeseen: x on hanketoimiston pohjaehdotus, D on Duodecimin ehdotus ja DH on hengitystieoirearvioon oleva ehdotus.

**Comment by jaakkokorhonen** [comment]
tarvittaneen lisättäviä koodeja jne

**Comment by jarinumminen** [comment]
Palvelukoodit on hengitysoirearviolla activityDefinitioneina. Lisäksi mukana tulee toistaiseksi kiirellisyyden ilmaiseva koodi P0-P3. Näiden kombinaatiot teoriassa mahdoton hallita. Avataan kiireellisyyden käsittelystä eri tiketti.
