### ISSUE TITLE
SELVITÄ miten lomakkeet julkaistaan riittävällä SLA:lla ja kapasiteetilla?

### ISSUE THREAD

**Issue by jaakkokorhonen** [omahoito/rfc#32]

**Comment by jarinumminen** [comment]
ODA1 pushaa lomakkeet ODA2:lle, jossa on käytössä olevat versiot lomakkeista. Muutos toteutuu 13.4. mennessä.

**Comment by jarinumminen** [comment]
Muutos toteutettu ja toimii. Siltä osin tämä asia on kunnossa.
