### ISSUE TITLE
KIRJOITA sisällönjulkaisusuunnitelma

### ISSUE THREAD

**Issue by jaakkokorhonen** [omahoito/rfc#34]
KIRJOITA .md -tiedosto tähän rfc-repoon, josta ilmenee ODA1 sisällönjulkaisusuunnitelma.

**Comment by jarinumminen** [comment]
ODA1_julkaisusuunnitelma.md on lisätty ja sitä täydennetään aina, kun tulee uutta tietoa

**Comment by jaakkokorhonen** [comment]
https://github.com/omahoito/rfc/blob/master/ODA1_julkaisusuunnitelma.md
