### ISSUE TITLE
Kuvaa päätöksentuen rajapintojen HTML-sisältö

### ISSUE THREAD

**Issue by jokimaki** [omahoito/rfc#35]
Missä päätöksentuen rajapintojen elementeissä voi palautua HTML-sisältöä? Mitkä ovat sallittuja elementtejä ja niiden sallitut attribuutit?

Jos sisällössä on img-elementtejä, voidaanko linjata että viittaukset ovat HTTPS-osoitteita?

Viitaten #13 #16 ja #19

**Comment by jarinumminen** [comment]
Tähänkin vielä kuittaus, että HTML-osalta valmis, jotta voi sulkea.

**Comment by jokimaki** [comment]
Pyytäisin dokumentoimaan [rajapintakuvaukseen](https://github.com/omahoito/rfc/blob/master/ODA1-API.swagger.yaml) missä kentissä HTML tai Markdown sisältöä on.

**Comment by vlindhol** [comment]
Tehdään se vielä, kuittaan tänne kun done.
