### ISSUE TITLE
Hengitystieoirearvio Questionnaire

### ISSUE THREAD

**Issue by jukkap-mc** [omahoito/rfc#36]
Toteutuksen suunnittelua varten tarvitaan FHIR Questionnaire resurssi hengitystieinfektio-oirearviolomakkeesta

**Comment by jaakkokorhonen** [comment]
Tarvitaan rajapinta joka palauttaa jotain oikeaa dataa. Oikeata lomaketta tarvitaan, jotta voidaan suunnitella mitä tietoja tarvitaan esitäyttöön, miten UI:ta rakennetaan jne.  Saadaanko @jarinumminen asialle joku aikataulu?

**Comment by jarinumminen** [comment]
Saadaan ensimmäinen, mutta ei vielä lopullinen versio nopeasti (lähipäivinä) ja uusi versio päivittyy rajapintaan, kun se saadaan valmiiksi. Samalla tulee testatuksi Vakioitujen kysymysten tietokannan rajapinta.

**Comment by jaakkokorhonen** [comment]
Mitäköhän tälle kuuluu? @Tomkinen @jarinumminen 
@kainutom odottelee rajapintaa nälkäisenä.

**Comment by jarinumminen** [comment]
Savutestaus siis tehty ja ODA1-päätä korjataan. Hengitystien oirearvion ensimmäinen versio tulee ladattavaksi tietokannasta viikon 13 alkupuoliskolla.

**Comment by kainutom** [comment]
Hengitystietulehdusoireiden itsearvio: 
http://www.ebmeds.org/form/api/forms/export/107/28

Lomakkeesta rakenteellisen validoinnin kautta saadut virheilmoitukset:

### 1. Virheilmoitus:
``` 
Failed to parse message body. 
Error was: Failed to parse JSON encoded FHIR content: com.google.gson.stream.MalformedJsonException:
Use JsonReader.setLenient(true) to accept malformed JSON at line 1302 column 2 path $
```
#### Ratkaisuehdotus:
Voiko "selfcare" ja "copyright" extensiot erottaa omiksi laajennoksi?
- Lomakkeella oleva yhdistetty rakenne ei ole Extension-elementin mukainen
- FHIR 3.0ssa on uusi elementti "copyright" jota voi hyödyntää jatkossa. 
Jos Extensiot on eriytetty, on copyright laajennos helposti korvattavissa copyright elementillä esim. näin:
``` 
	"extension": [{
			"url": "https://www.ebmeds.org/form#selfCareInstructions",
			"extension": [{
					"url": "instruction_text",
					"valueString": "<a href=\"http://www.terveyskirjasto.fi/terveyskirjasto/tk.koti?p_artikkeli=dlk01167\">Itsehoito-ohje</a>."
				}, {
					"url": "instruction_url",
					"valueString": null
				}
			]
		}
	],
	"extension": [{
			"url": "https://www.ebmeds.org/form#copyright",
			"valueString": null		
		}
	]	  
``` 	
### 2. Virheilmoitus:
```
Failed to parse message body. Error was: Syntax error parsing JSON FHIR structure: Expected ARRAY at element 'extension', found 'OBJECT'
```
#### Ratkaisuehdotus:
- Extension-elementit eivät ole FHIRin mukaisia (ongelma esiintyy monessa kohtaa).
- Näyttäisi että elemnetistä puuttuu hakasulkeet
- Voidaan korjata esim. näin:
``` 
      "extension":[
					{
					"url": "answer_type",
					"valueString": "subtitle"
					}
				]
``` 
				
### 3. Virheilmoitus:
      "severity": "error",
      "code": "processing",
      "diagnostics": "This property must be an simple value, not a com.google.gson.JsonNull",
      "location": [
        "/Questionnaire/extension/value[x]"
      ]

#### Ratkaisuehdotus:
- Extensioneiden arvot (esim. valueString) eivät voi olla "null"
- Poistetaan nämä kokonaan jos niille ei ole käyttöä tai lisättävä arvot esim. näin:
``` 
      "extension": [{
			"url": "https://www.ebmeds.org/form#copyright",
			"valueString": "sometext"
		}
	]
``` 	
	
### 4. Virheilmoitus:
      "severity": "error",
      "code": "processing",
      "diagnostics": "Error parsing JSON: the primitive value must be a string",
      "location": [
        "/Questionnaire/identifier/value"
      ]

Ratkaisusehdotus:
- Lomakkeen tunnisteen arvo on oltava merkkijono
- Muutetaan arvo merkkijonoksi esim. näin:
``` 
      "identifier": [{
			"system": "https://www.ebmeds.org/form/api/FHIR/forms/export/107",
			"value": "107"
		}
	  ]
``` 	
### 5. Virheilmoitus:
	  "severity": "error",
      "code": "processing",
      "diagnostics": "Error parsing JSON: the primitive value must be a string",
      "location": [
        "/Questionnaire/item/item/linkId"
      ]
	  
Ratkaisusehdotus: 
- Sama kuin kohdassa 4

### 6. Virheilmoitus:
	  "severity": "error",
      "code": "processing",
      "diagnostics": "Unrecognised property '@Coding'",
      "location": [
        "/Questionnaire/item/item/concept"
      ]
Ratkaisusehdotus: 
- Concept elementti ei ole FHIRin mukainen
- Poistetaan "Coding" "concep":n sisältä esim.:
``` 
      "concept": {
				"system": null,
				"display": null,
				"code": null
				} 
``` 
### 7. Virheilmoitukset:
    {
      "severity": "error",
      "code": "processing",
      "diagnostics": "This property must be an simple value, not a com.google.gson.JsonNull",
      "location": [
        "/Questionnaire/item/item/concept/system"
      ]
    },
    {
      "severity": "error",
      "code": "processing",
      "diagnostics": "This property must be an simple value, not a com.google.gson.JsonNull",
      "location": [
        "/Questionnaire/item/item/concept/code"
      ]
    },
    {
      "severity": "error",
      "code": "processing",
      "diagnostics": "This property must be an simple value, not a com.google.gson.JsonNull",
      "location": [
        "/Questionnaire/item/item/concept/display"
      ]
    }

#### Ratkaisuehdotus:
- Concept elementin "display", "code" ja "system" eivät voi olla "null"
- Poistetaan concept elementit kokonaan jos niille ei ole tarvetta tai asetetaan niihin tarkoituksenmukaiset koodit esim.:
``` 
		"concept": {
						"system": "http://www.ebmeds.org/form#selfCareCodeSystem",
						"display": "display value",
						"code": "someCode"
					}
``` 					
### 8. Virheilmoitus:
	  "severity": "error",
      "code": "processing",
      "diagnostics": "Unrecognised property '@operator'",
      "location": [
        "/Questionnaire/item/item/enableWhen"
      ]

#### Ratkaisuehdotus:
- Poistetaan turhat standardin vastaiset "operator" määritykset (turhia ovat ne joissa operator=null)
- Poistetaan standardin vastaiset "operator" määritykset joilla ilmaistaan "OR" ehdollisuutta, koska standardin mukaan 
usea "enableWhen" tulkitaan automaattisesti "OR":
``` 
'If multiple repetitions of this extension are present, the item should be enabled when the condition for any of the repetitions is true.
I.e. treat "enableWhen"s as being joined by an "or" clause.'
``` 
https://www.hl7.org/fhir/questionnaire-definitions.html#Questionnaire.item.enableWhen

- Ilmaistaan "AND" operator määritykset Extensiona esim. ("OR" operatorit myös mahdollista määrittää näin jos haluaa):
``` 
				"extension":[{
								"url": "https://www.ebmeds.org/form#enableWhenOperator",
								"valueString": "AND"
								}
							]
``` 
- "Oikeampi" tapa kai olisi käyttää näihin monimutkaisiin evaluointeihin säännöllisiä lausekkeita, mutta näillä Extensioillakin varmaan ensihätään onnistuu

### 9. Virheilmoitus:
	  "severity": "error",
      "code": "processing",
      "diagnostics": "Unrecognised property '@answerReference'",
      "location": [
        "/Questionnaire/item/item/enableWhen"
      ]

#### Ratkaisuehdotus:
- AnswerReference ei vastaa standardia
- EnabWhen ei voi sisältää kahta eri vastaustyyppiä (answerString & answerQuantity)
- Poistetaan "answerString" 
- Muutetaan "answerReference" standardin mukaisiksi esim. "answerQuantity":
```  
			"enableWhen": [{
							"question": "3",
							"answerQuantity": {
								"value": 15,
								"comparator": "<"
							}
						}
					]
``` 				
### 10. Virheilmoitus:
	  "severity": "error",
      "code": "processing",
      "diagnostics": "Error parsing JSON: the primitive value must be a boolean",
      "location": [
        "/Questionnaire/item/item/repeats"
      ]

#### Ratkaisuehdotus:
- Korjataan merkkijonot standardin mukaisiksi boolean arvoiksi esim.: "repeats": false

### 11. Virheilmoitus:
	  "severity": "error",
      "code": "processing",
      "diagnostics": "Error parsing JSON: the primitive value must be a string",
      "location": [
        "/Questionnaire/item/item/option/value[x]/id"
      ]
#### Ratkaisuehdotus:
- Korjataan numeroarvot standardin mukaisiksi merkkijonoiksi esim.: "id": "35"

### 12. Virheilmoitukset:
    {
      "severity": "error",
      "code": "processing",
      "diagnostics": "This property must be an simple value, not a com.google.gson.JsonNull",
      "location": [
        "/Questionnaire/item/item/option/value[x]/system"
      ]
    },
    {
      "severity": "error",
      "code": "processing",
      "diagnostics": "This property must be an simple value, not a com.google.gson.JsonNull",
      "location": [
        "/Questionnaire/item/item/option/value[x]/code"
      ]
#### Ratkaisuehdotus:
- Asetetaan koodistoarvot tai poistetaan "code" ja "system" jos niille ei ole tarpeen määrittää arvoja

### 13. Virheilmoitus:
	  "severity": "error",
      "code": "processing",
      "diagnostics": "This property must be an simple value, not a com.google.gson.JsonNull",
      "location": [
        "/Questionnaire/item/item/text"
      ]
#### Ratkaisuehdotus:
- Asetetaan merkkijonoarvo tai poistetaan "text" jos sille ei ole tarpeen määrittää arvoa

### 14. Virheilmoitus:
	  "severity": "error",
      "code": "processing",
      "diagnostics": "Unrecognised property '@code'",
      "location": [
        "/Questionnaire"
      ]
#### Ratkaisuehdotus:
- Poistetaan "code" jos sille ei ole mitään käyttötarvetta tai korvataan standardin mukaisella rakenteella

### 15. Virheilmoitus:
	  "severity": "error",
      "code": "processing",
      "diagnostics": "Wrong namespace on the XHTML ('null')",
      "location": [
        "Questionnaire.text.div"
      ]
#### Ratkaisuehdotus:
- Lisätään namespace esim.: "div": "<div xmlns=\"http://www.w3.org/1999/xhtml\">null</div>

### 16. Virheilmoitus:
	  "severity": "error",
      "code": "processing",
      "diagnostics": "Must have either extensions or value[x], not both [extension.exists() != value.exists()]",
      "location": [
        "Questionnaire.item.item[14].option[1].extension"
      ]
	  
#### Ratkaisuehdotus:
- Mihin extensiota tarvitaan "option":ssa? Jos ei ole tarvetta poistetaan ne.

### 17. Virheilmoitus:
	  "severity": "error",
      "code": "processing",
      "diagnostics": "Coding.system must be an absolute reference, not a local reference",
      "location": [
        "Questionnaire.item.item[19].concept"
      ]
#### Ratkaisuehdotus:
- Korjataan "system" arvo esim.:
``` 
	"concept": {
				"system": "urn:1.2.246.537.6.96",
				"display": "finLOINC",
				"code": "8310-5"
				}	 
```

**Comment by vlindhol** [comment]
[Tässä korjattu versio Questionnaire 107:sta.](https://github.com/omahoito/rfc/files/889342/questionnaire-107-fixed.json.zip) Se on zipattu koska github ei suostunut muuten. Kiitos @kainutom kattavasta raportista! Sain tämän version puskettua HAPI-serverill ongelmitta, löytyy nyt url:in "Questionnaire/257/_history/1" takaa. @Tomkinen on lomalla ja palaa torstaina, joten VKT:n muutokset saadaan vasta sen jälkeen (minulla ei ole pääsy siihen koodiin).

Alla kommentit jokaiseen virheilmoituskohtaan:

1. Copyright-extension on turha, se on poistettu. Löytyy tosiaan se oma copyright-kenttä nykyään. (Sen unohdin itse asiassa asettaa tässä esimerkissä, mutta copyright tulee kyllä mukaan.)
2. Korjattu.
3. `"valueString": null` laitettu `"valueString": "null"`:iksi ainakin väliaikaisesti, katsotaan vielä mitkä voisi poistaa kokonaan.
4. Korjattu.
5. Korjattu.
6. Korjattu.
7. null-conceptit poistettu. Mietitään täytyykö antaa niille arvo poistamisen sijaan.
8. null-operaattorit poistettu, OR-operaattorit poistettu (default-käyttäytyminen oli aina riittävä tässä kyselyssä). AND-operaattori lisätty extensiona. ORkin täytyy lisätä tälleen jos sille löytyy tarve muissa kyselyissä.
9. Korjattu.
10. Korjattu.
11. Korjattu.
12. Nullit poistettu. Mietitään tarvitaanko asettaa näille arvoja.
13. Nullit poistettu.
14. Poistettu, sama tieto löytyy `identifier`ista.
15. Korjattu.
16. En tiedä tästä, poistettu tässä esimerkissä.
17. Korjattu.

Toivottavasti tällä pääsee eteenpäin, @Tomkinen ottaa kopin tästä kunhan palaa lomalta.

**Comment by jokimaki** [comment]
Muutama sisällöllinen ongelma:
- Dropboxiin osoittava linkki (dl.dropboxusercontent.com/.../Kurkkukipukyselyn%20kuvat.png). Olisi hyvä julkaista pysyvämmästä paikasta?
- Linkki josta puuttuu protokolla (href="www.terveyskirjasto.fi...") ei tule toimimaan
- Kuvien src:t viittaavat http-osoitteisiin, mikä tulee aiheuttamaan selainmessa varoituksen kun sivusto tarjoillaan https:llä.

**Comment by kainutom** [comment]
Täytyy tunnistaa globaalisti että missä kysymyksissä kysytään esim. ikää. Kysymyksiä siis olisi hyvä koodittaa (ainakin "ikä" kooditus olisi tarpeellinen) jotta ne voidaan täyttää ohjelmallisesti.

**Comment by Tomkinen** [comment]
ODA1 sprint 9 item DO-102. Korjaus parhaillaan työn alla. Ilmoitan kun voidaan testailla jahka saan rajapinnan koodit korjattua.

**Comment by Tomkinen** [comment]
FHIR export rajapinta korjattu VKT:n backendissä. Liitteenä tuotannossa generoitu oirekyselylomake 107.
[questionnaire_107_after_fix_110417.json.zip](https://github.com/omahoito/rfc/files/912911/questionnaire_107_after_fix_110417.json.zip)

**Comment by Tomkinen** [comment]
Sisällöllisistä ongelmista välitin viestin Johannekselle ja Ilkalle.

**Comment by Tomkinen** [comment]
Liitteenä uusi versio johon on korjattu kaikki mitä Kainulaisen kanssa keskusteltiin Slackissä. Nyt pitäisi olla kaikki kunnossa. Ainakin kaikki on tehty mitä on ilmoitettu virheiksi.

-answerQuantity on nyt Number, ei String. Korjattu.
-Copyright poistettu fhir-rajapinnasta.
-Concept on nyt array (sisältää [] -sulkeet).

[questionnaire_107_120417.json.zip](https://github.com/omahoito/rfc/files/916241/questionnaire_107_120417.json.zip)

**Comment by jarinumminen** [comment]
oirearvio on käytössä
