### ISSUE TITLE
Poista syntymäajan ja sukupuolen legacy-vaatimus

### ISSUE THREAD

**Issue by jaakkokorhonen** [omahoito/rfc#45]
Poista syntymäajan ja sukupuolen legacy-vaatimus niin että nämä tiedot kysytään questionnairessa vain silloin kun tarvitaan.

**Comment by jarinumminen** [comment]
Vielä kuittaus, että tämä on tehty, niin voin sulkea.

**Comment by vlindhol** [comment]
Done.
