### ISSUE TITLE
Kooditussysteemien formaatti ODA1-ODA2 FHIR-kommunikaatiossa

### ISSUE THREAD

**Issue by vlindhol** [omahoito/rfc#55]
Kun validoin palauttamiamme ActivityDefinitioneita selvisi, että `code`-kentässä olevien `system`-arvot (eli kooditussysteemit) eivät olleet standardin mukaisia. Tähän asti ollaan palautettu vain raaka OID-arvo, esim `1.2.246.537.6.49`, mutta FHIR haluaa URI:n.

Validointia voi läpäistä quick and dirty laittamalla `urn:oid:` sen koodin eteen, mutta jos halutaan olla oikeaoppisia niin pitäisi noudattaa [tätä algoritmia](https://www.hl7.org/fhir/terminologies.html#system):

 1) If the code system is found in https://www.hl7.org/fhir/terminologies-systems.html use the URL provided there.
2) If the publisher of the code system has defined a specific URL to use with FHIR, use that.
3) If the code system can be found in http://registry.fhir.org/NamingSystem and its status is active, use that.
4) If an OID is registered at http://hl7.org/oid use the form 'urn:oid:[oid]' where [oid] is the original OID.
5) If all else fails, come up with your own unique URL.

[Tässä gistissä](https://gist.github.com/vlindhol/09290d2386946e06ad21919f6c28bb86) olen yrittänyt mäpätä OID:t ylläolevan algoritmin mukaisesti. Kaikkia systeemejä ei välttämättä käytetä MVP:ssä tai edes ODA:ssa, mutta ainakin kotimaan koodisysteemit olisi hyvä määrittää hyvin. Juuri nyt esim. FinLOINC ja KL käyttävät keksittyä URL:ää, ja Suomen versio ICD-10:stä on varmaan syytä huomioida erikseen, nyt laitettu FHIR:in oma ICD10-url sinne.

Tiedoston lopussa on meidän custom-koodit, eli pieniä sisäisiä koodistoja jotka tulevat tarpeen FHIR-viesteissä. Niiden nimiä voi vielä viilata jos haluaa.

Pyydän siis inputtia sekä Duodecimin sisällöntuottajilta että ODA:n puolelta, kommentoikaa tähän issueen tai suoraan Gistiin. Tässä linkki vielä kerran: https://gist.github.com/vlindhol/09290d2386946e06ad21919f6c28bb86

**Comment by jarinumminen** [comment]
Periaate on hyvä, noudattaa kansainvälistä yhteensopivuutta ensisijaisesti. ICD-10 kannattanee katsoa koodistopalvelimelta: http://91.202.112.142/codeserver/pages/classification-view-page.xhtml?classificationKey=23&versionKey=58

**Comment by joomak** [comment]
ICD-10-koodiston kansallisen viittauksen voisi tehdä kuten täällä https://www.hl7.org/fhir/icd.html on esimerkkinä Saksan ja Hollannin koodistoille variantit, esim.

http://hl7.org/fhir/sid/icd-10
http://hl7.org/fhir/sid/icd-10-de
http://hl7.org/fhir/sid/icd-10-nl

Suomen ICD-10 olisi siten
http://hl7.org/fhir/sid/icd-10-fi

Linkit eivät ole toimivia.

**Comment by vlindhol** [comment]
Se gist on nyt päivitetty nykytilanteeseen: https://gist.github.com/vlindhol/09290d2386946e06ad21919f6c28bb86
