### ISSUE TITLE
Oirearvioiden validointivirheet

### ISSUE THREAD

**Issue by kainutom** [omahoito/rfc#84]
Oirearviot 21, 22, 41, 27:
"issue": [ { "severity": "error", "code": "processing", "diagnostics": "Failed to parse request body as JSON resource. Error was: Invalid attribute value \"\": Attribute values must not be empty (\"\")" }

Oirearvio 2:
Invalid attribute value "": Attribute values must not be empty ("")

Oirearvio 124:
"diagnostics": "ca.uhn.fhir.parser.DataFormatException: String does not appear to be valid XML/XHTML (error is \"Unexpected close tag </div>; expected </br>.\r\n at [row,col {unknown-source}]: [1,233]\"): <div xmlns=\"http://www.w3.org/1999/xhtml\">Neuvova itsearviointilomake, joka auttaa potilasta arvioimaan ammattiavun tarvetta ja omahoidon mahdollisuuksia silmäoireiden yhteydessä. Lomake soveltuu vain 15 vuotta täyttäneille.<br></div>"

**Comment by Tomkinen** [comment]
Oirearviot 21, 22, 41 ja 27 eivät enää sisällä tyhjiä. Korjattu vkt fhir exportin generointikoodiin. Lomakkeet tulee julkaista uudestaan vkt käyttöliittymässä jotta fhir muoto päivittyy rajapinnassa.

**Comment by Tomkinen** [comment]
Oirearvion 2 tyhjän arvon aiheuttanut koodi korjattu. Testattu devissä. Tarvitsi koodimuutoksen vkt fhir exportin generointikoodiin. Ei ole vielä tuotannossa. Ilmoitan kun tehty.

**Comment by Tomkinen** [comment]
Oirearvion 124 teksti korjattu.

**Comment by Tomkinen** [comment]
Koodit on nyt tuotantoympäristössä ajossa. Uudelleen julkaisu pitää vielä suorittaa lomakkeille.

**Comment by Tomkinen** [comment]
Oirekyselyt on julkaistu uudestaan. Testatkaa oda2 päässä toimiiko kaikki kuten pitää.

**Comment by kainutom** [comment]
Onko nämä validoitu ODA2:sta vasten?

**Comment by kainutom** [comment]
Nämä ok lomakkeiden osalta. Tämän voi sulkea @jarinumminen . Tein toimintosuosituksesta oman issuen: https://github.com/omahoito/rfc/issues/96

**Comment by jarinumminen** [comment]
suljetaan
