### ISSUE TITLE
Oirearvioiden identifier system on virheellinen

### ISSUE THREAD

**Issue by kainutom** [omahoito/rfc#85]
Palautteet vaatii toimiakseen muodon: https://duodecim.fi/fhir/sid/vkt-questionnaire-id Tällä hetkellä useassa airearviossa on: http://duodecim.fi/fhir/sid/vkt-questionnaire-id

**Comment by Tomkinen** [comment]
Tämä on koodissa oikein, eli on uudelleen julkaisua vailla valmis. Ei vaadi koodimuutoksia vkt:hen. Korjaantuu osana uudelleenjulkaisuja (jotka tehdään muiden issueiden ratkaisun yhteydessä).

**Comment by Tomkinen** [comment]
Lomakkeet julkaistu uudestaan. Tarkistakaa että urli on nyt oikien.

**Comment by kainutom** [comment]
Tämä ok

**Comment by jarinumminen** [comment]
suljetaan.
