### ISSUE TITLE
Oirearvioihin versionumero

### ISSUE THREAD

**Issue by kainutom** [omahoito/rfc#86]
Oirearvioihin tarvitaan mukaan versionumero että tiedetään esim. millä versiolla eri pilotteja on tehty. Versionumero voi olla mahdollisesti suoraan VKT versionumero, joka lisätään Questionnairen "version" attribuutiksi.

**Comment by Tomkinen** [comment]
Oirearvioiden fhir expottiin lisätty versionumero. Versionumero on sama kuin mikä on VKT:n tietokantaan tallentuva yksittäisen fhir exportin versionumero. Uniikki id per julkaisu. Lomakkeet tulee julkaista uudelleen. Version generoivat koodit on tuotannossa ajossa.

**Comment by Tomkinen** [comment]
Oirekyselyt on nyt julkaistu uudelleen. Mukana versionumerot. Tulihan ne ok perille oda2 päähän?

**Comment by kainutom** [comment]
Tämä ok @jarinumminen

**Comment by jarinumminen** [comment]
Suljetaan.
