### ISSUE TITLE
Oirearvioihin metatiedot kategoriointia varten

### ISSUE THREAD

**Issue by kainutom** [omahoito/rfc#87]
Oirearvioiden kategoriointiin tarvitaan oda2:ssa metatietoja.
Olisiko oda1:ssä mahdollisuus lisätä oirearvioihin alla esitetyt metatiedot?
```
"meta": {
	"profile": [
		"http://phr.kanta.fi/StructureDefinition/fiphr-questionnaire-stu3"
	],
	"tag": [{
			"system": "http://oda.fi/Questionnaire",
			"code": "symptom"
		},
                {
			"system": "http://oda.fi/cds",
			"code": "oda1"
		}
	]
} 
```

**Comment by vlindhol** [comment]
Onko tämä aina sama metatieto, vai voiko noilla tageilla olla muitakin arvoja? @Tomkinen pystyy hoitamaan tän.

**Comment by kainutom** [comment]
Juu kaikille oirearvioille sama. Hyvinvoinnin arvioille ja hyvinvointitarkastuksille täytyy "symptom" koodin tilalle keksiä ja asettaa oma koodi.

**Comment by Tomkinen** [comment]
Lisätty fhir exporttiin meta ja sisällöt kuten issuessa kuvattu.

**Comment by Tomkinen** [comment]
Siirretty tuotantoon.

**Comment by Tomkinen** [comment]
Oirekyselyt lähetetty fhir muodossa uudestaan.

**Comment by kainutom** [comment]
Tämä ok @jarinumminen

**Comment by jarinumminen** [comment]
suljetaan
