### ISSUE TITLE
Oirearvio 22: "ohjetekstit" näkyy aina kun on vastattu "Arvelen tarvitsevani muuta hoitoa ..."

### ISSUE THREAD

**Issue by kainutom** [omahoito/rfc#88]
Seuraavat tekstit ovat aina näkyvissä kun ensimmäiseen kysymykseen vastataan "ARVELEN TARVITSEVANI MUUTA HOITOA JA HALUAN TÄYTTÄÄ OIREKYSELYN" : 

- Oireidesi perusteella sinun on aiheellista ottaa välittömästi yhteys päivystykseen. Jos vointisi sallii, voit antaa esitietoja tällä lomakkeella vastaamalla alla oleviin kysymyksiin.
- Jos kuumetta on yli 38,5 astetta, ota yhteyttä päivystykseen välittömästi. Muuten hakeudu päivystysvastaanotolle viimeistään seuraavana aamuna kuumeen edelleen jatkuessa.
- Antamiesi tietojen perusteella yleisvointisi on huonompi kuin yleensä flunssan yhteydessä. Jatka lomakkeen täyttämistä saadaksesi lisäohjeita ja yhteyden ammattilaiseen viimeistään vuorokauden kuluessa.

**Comment by Tomkinen** [comment]
Korjaus tehty VKT:n FHIR exporttiin. Nyt lähtee fhir muodossa jossa mukana on:
item->item->enableWhen->extension (enable-when-operator) valueString='AND'

Tämä tehtiin jotta VKT:n sisäinen lomakkeen esikatselu ja ODA2 käyttöliittymä toimisivat samalla tavalla.

Odottaa tuotantoon siirtoa.

**Comment by Tomkinen** [comment]
Siirretty tuotantoon. Johannes tekee tarvittaville lomakkeille julkaisun (FHIR viestit lähtee ODA2:lle). Koodit on kunnossa ja tuotanto valmis lähettämään korjattua FHIR dataa.

**Comment by Tomkinen** [comment]
Julkaisu suoritettu. Testatkaa vielä oda2 päässä.

**Comment by kainutom** [comment]
Tämä ok @jarinumminen

**Comment by jarinumminen** [comment]
suljetaan
