### ISSUE TITLE
Oirearvio 124: Kuva ei näy

### ISSUE THREAD

**Issue by kainutom** [omahoito/rfc#89]
"Verestävä silmä" ei näy. Ongelma ilmeisesti linkissä. "http://www.terveysportti.fi/xmedia/ima/370.121.jpg"
pitäisi olla "https://www.terveysportti.fi/xmedia/ima/370.121.jpg"

**Comment by Tomkinen** [comment]
Korjattu VKT:n käyttöliittymässä. Pitää vielä julkaista ennen kuin suljetaan tiketti.

**Comment by Tomkinen** [comment]
Julkaistu.

**Comment by kainutom** [comment]
Tämä ok @jarinumminen

**Comment by jarinumminen** [comment]
suljetaan
