### ISSUE TITLE
Oirearvio 41: null-arvo tekstikentässä

### ISSUE THREAD

**Issue by kainutom** [omahoito/rfc#90]
![image](https://user-images.githubusercontent.com/22096314/29819855-0e880d02-8ccb-11e7-9ac8-a2618ac14fdd.png)

**Comment by Tomkinen** [comment]
Korjattu koodiin ja kehitysympäristössä testattu. Enää ei tulee null tähän kenttään (väliotsikon leipäteksti) fhir exportissa oda2:lle vkt:sta.

**Comment by Tomkinen** [comment]
Tuotantoon siirto tehty. Lomake pitää vielä julkaista uudestaan.

**Comment by Tomkinen** [comment]
Lomake julkaistu uudestaan. Null arvoa ei enää ole mukana.Tarkistakaa vielä oda2 päässä. Puolestani issue on käsitelty.

**Comment by kainutom** [comment]
Tämä ok @jarinumminen

**Comment by jarinumminen** [comment]
suljetaan
