### ISSUE TITLE
Oirearvio 22: alle 15-vuotiasta kehoitetaan vastaamaan olemattomiin "alla oleviin kysymyksiin"

### ISSUE THREAD

**Issue by kainutom** [omahoito/rfc#92]
![image](https://user-images.githubusercontent.com/22096314/29857376-0287f76a-8d61-11e7-9254-5b7ec44c6086.png)

**Comment by kainutom** [comment]
Tämä saattoi olla vain vanhan version ongelma, tarkistettava uusimmalla versiolla uudestaan

**Comment by Tomkinen** [comment]
Tämä on korjattu. Korjatut koodit tuotannossa. Odottaa uudelleen lähetystä vkt->oda2.

**Comment by Tomkinen** [comment]
Lomake julkaistu uudestaan. enableWhen elementit fhir exportissa on nyt oikein. Tarkistakaa vielä oda2 päässä. Puolestani issue on käsitelty.

**Comment by kainutom** [comment]
Tämä toimii edelleen kuvassa esitetyllä tavalla. Ongelma ei ole varsinaisesti enablewhenissä vaan kaiketi sisällössä.
"Oireidesi perusteella sinun on aiheellista ottaa välittömästi yhteys päivystykseen. Jos vointisi sallii, voit antaa esitietoja tällä lomakkeella vastaamalla alla oleviin kysymyksiin." -teksti näytetään kaikille jos on vastannut "Kyllä" noihin kuvassa oleviin kysymyksiin kaiken ikäisille. Alle 15-vuotiaalta on kuitenkin rajattu jatkokysymykset pois. @Tomkinen @jarinumminen

**Comment by jarinumminen** [comment]
Vika taitaa olla siinä, että kaksi ensimmäistä kriittistä kysymystä ei huomioi ikää eli kysymykset nro 5 ja 6 @Tomkinen

**Comment by Wildarts** [comment]
Yllä olevat virheet on korjattu ja uusi versio lomakkeesta on julkaistu

**Comment by Tomkinen** [comment]
Johannes on korjannut sisältöongelman. Voidaanko tämä tiketti sulkea? Voisitko vielä testata? VKT:ssa näyttää olevan kysymyksillä 5 ja 6 näyttölogiikat nyt oikein.

**Comment by Wildarts** [comment]
Omasta puolestani tiketin voi sulkea. Olen testannut, että näyttölogiikka toimii (ainakin VKT:ssa) toivotulla tavalla. Uusi versio oirekyselystä on julkaistu eilen. 

Huomauttaisin tässä kohtaa kuitenkin siitä, että näyttölogiikan rakenteesta johtuen on joskus mahdollista, että vastausvaihtoehdot jäävät epäloogisesti näkyviin jos käyttäjä palaa muuttamaan aikaisempia vastauksiaan. VKT:ssa on tällä hetkellä käytössä toteutus, jossa jokaisella kysymyksellä on visibility-parametri ja jotta tiettyyn kysymykseen liittyvät näyttölogiikat tulkitaan, tulee kyseisen kysymyksen olla näkyvissä. 

Esim: 
Kysymys 1: Haluatko vastata kyselyyn?
Kysymys 2: Sukupuoli? (näytetään vain jos 1. vastaus on "kyllä")
Kysymys 3: Oletko raskaana? (näytetään vain naisille)

Jos käyttäjä vastaa ensin kysymykseen 1. "kyllä" ja kysymykseen 2. "nainen" ja sen jälkeen muuttaa kysymyksen yksi vastaukseksi "ei", jää kysymys 3. kuitenkin näkyviin (koska kysymyksen 2. vastaus on edelleen "nainen"). 

VKT:ssa on käytössä visibility-parametri, joten edellä kuvatussa tilanteessa kysymys 3. EI jää näkyviin, koska kysymyksen 2. visibility muuttuu kun kysymyksen 1. vastaus muutetaan. 

Onko vastaava toteutus käytössä ODA2:n käyttöliittymässä? Jos ei ole, niin tämä olisi syytä toteuttaa.

**Comment by kainutom** [comment]
Tämä on ok @jarinumminen

**Comment by jarinumminen** [comment]
suljetaan
