### ISSUE TITLE
Oirearvio 21: Lisätietoa on pakko kirjata vaikka kysymystekstin perusteella näin ei ole

### ISSUE THREAD

**Issue by kainutom** [omahoito/rfc#93]
![image](https://user-images.githubusercontent.com/22096314/29913637-58f9796a-8e3e-11e7-9b12-a8b4652832bb.png)

**Comment by Tomkinen** [comment]
FHIR exportissa VKT -> ODA2 määritellään item->item->required=true.

VKT käyttöliittymässä ei ole mahdollista asettaa kysymykseen vastaamista pakolliseksi/optionaaliseksi. Tällaista ominaisuutta ei ole. Konsultoin Johannesta tuleeko tällainen uusi ominaisuus koodata, vai muokataanko tätä lomaketta. Joskus muistan olleen puhetta että kaikki kysymykset olisi pakollisia. Palaan asiaan.

**Comment by Wildarts** [comment]
Aiemmin on tosiaan puhuttu siitä että (lähes) kaikkiin kysymyksiin vastaaminen olisi pakollista. Käytännössä kaikki skriptilogiikassa käytettävät kysymykset tulisi olla täytettyinä, koska muuten näiden tulkinta menee erittäin hankalaksi. Joidenkin oirekyselyiden lopussa on kuitenkin kysymyksiä, jotka ovat selvästi optionaalisia. Olisikohan ongelma kierrettävissä niin, että vapaat tekstikentät voivat aina olla tyhjiä? Emme kuitenkaan pysty validoimaan niiden sisältöä muilta osin. Jos tämä ei ratkaise ongelmaa, niin siinä tapauksessa joudutaan todennäköisesti tekemään lisäys VKT:hen.

**Comment by Tomkinen** [comment]
Kyllä onnistuu. Voin fhir exportissa poistaa item->item->required=true -kohdan jos kyseessä on vapaatekstikenttä tai vapaatekstialue. Saako suorittaa?

**Comment by Wildarts** [comment]
Saa suorittaa.

**Comment by Tomkinen** [comment]
Suoritan. Ilmoitan kun suoritettu.

**Comment by Tomkinen** [comment]
Suoritettu. Siirretty tuotantoon. Nyt jos julkaisee lomakkeen, kaikki text tai textarea -tyyppiset kysymykset eivät ole merkitty fhir-eksportissa pakollisiksi. Lomake tulee vielä julkaista uudestaan.

**Comment by Tomkinen** [comment]
Lomake julkaistu uudestaan. Ei sisällä enää issuen kuvauksessa mainitun kysymyksen kohdalla että olisi required. Tarkistakaa vielä oda2 päässä. Puolestani issue on käsitelty.

**Comment by kainutom** [comment]
Toimii ok @jarinumminen

**Comment by jarinumminen** [comment]
suljetaan
