### ISSUE TITLE
Oirearvioiden toimintosuositusten validoinnissa virhe

### ISSUE THREAD

**Issue by kainutom** [omahoito/rfc#96]
Oirearvioiden toimintosuositusten validoinnissa virhe:
"issue": [ { "severity": "error", "code": "processing", "diagnostics": "Object must have some content", "location": [ "/ActivityDefinition/timing[x]" ] }, { "severity": "error", "code": "processing", "diagnostics": "This property must be an Object, not a com.google.gson.JsonPrimitive", "location": [ "/ActivityDefinition/participant/role" ] } ]

**Comment by vlindhol** [comment]
Fixed in latest test version of ODA1.
