### ISSUE TITLE
Terveystarkastus 153: rakennehuomiot

### ISSUE THREAD

**Issue by kainutom** [omahoito/rfc#97]
- lomakkeen kategoria puuttuu (onko tarvetta määrittää eri kategoriaan kuin varsinaiset oirearviot? https://github.com/omahoito/rfc/issues/87)
- validoinnissa virhe:  Invalid attribute value "": Attribute values must not be empty ("")
- lomakkeen versio puuttuu
- null tekstit 10kpl
![image](https://user-images.githubusercontent.com/22096314/30016753-170ddc34-915f-11e7-8ecb-3882e3a51862.png)
![image](https://user-images.githubusercontent.com/22096314/30016821-53fdf3ea-915f-11e7-9625-0ebb626f4f57.png)

Jokunen ongelma varmasti korjaantuu "itsestään" uudelleen julkaisulla (?)

**Comment by Tomkinen** [comment]
Kategoriatiedot tulevat json fhir viestin mukana kun lomake julkaistaan vaan uudestaan.

Sama tyhjien attribuuttien kanssa. Korjaantuu uudelleen julkaisulla.

Versiotieto on mukana ja null tekstit putoaa pois jos lomake julkaistaan uudestaan.

Kaikki mainitut ongelmat näyttää korjaantuvan uudelleen julkaisulla. Pyydän Johannesta uudelleen julkaisemaan.

**Comment by Tomkinen** [comment]
Lomake julkaistu uudestaan. FHIR lähti VKT:sta ODA2:een.

**Comment by kainutom** [comment]
Validoinnissa edelleen virhe: Invalid attribute value "": Attribute values must not be empty ("")

**Comment by Tomkinen** [comment]
Korjattu koodiin ja testattu devissä. Jos käyttöliittymässä jättää kyseisen kentän tyhjäksi, FHIR exporttiin ei tule text-attribuuttia ollenkaan. Koodi ei ole vielä tuotantoympäristöön siirretty. Ilmoitan kun tehty.

**Comment by Tomkinen** [comment]
Tuotantoon siirto tehty. Lomake julkaistu. Onko nyt ok?

**Comment by kainutom** [comment]
Nämä ok @jarinumminen

**Comment by jarinumminen** [comment]
suljetaan
