### ISSUE TITLE
Terveystarkastus 153: sisällölliset huomiot

### ISSUE THREAD

**Issue by kainutom** [omahoito/rfc#98]
Muutamia "käyttäjän" huomioita sisällöstä:
- Voiko kysymystä "Kuinka pitkä olet?" tarkentaa esim. "Kuinka pitkä olet (cm)?" tai lisätä esimerkin vastausmuodosta. Onko vastausmuodolla merkitystä? 175 vs 1.75 vs 1,75
- Muissakin kiloja tai senttejä koskevissa kysymyksissä voisi esimerkki tai tarkennus kirjaamismuodosta
- Onko mahdollista lisätä "En tiedä" vaihtoehto? Mikä on angina pectoris? Kaikki eivät välttämättä osaa vastata näihin ja vastauksen pakollisuus estää lomakkeen lähetyksen :
![image](https://user-images.githubusercontent.com/22096314/30017223-fd708e3c-9160-11e7-8d0e-acdf948d563e.png)

**Comment by Wildarts** [comment]
Kysymyksissä joiden vastaus on vapaa tekstikenttä, tulisi vastauskenttä ehdottomasti toteuttaa niin, että sen sisältö validoidaan automaattisesti. Esim. ikäkenttään tulisi pystyä syöttämään ainoastaan positiivinen kokonaisluku väliltä 0-120, painoon tai pituuteen positiivinen rationaaliluku väliltä 0-250 jne. Skriptilogiikka ei toimi, jos kenttä palauttaa string-arvon. 

Muutan kysymykset niin, että niissä mainitaan aina toivottu yksikkö. 

Olemme lisänneet joihinkin oirekyselyiden kysymyksiin jo tuon "En tiedä" vaihtoehdon. Tämän haittapuoli on se, että se komplisoi vastausten tulkintaa ja muotoilua. Raskaudessa tulkinta on yleensä rakennettu niin, että "En tiedä" = "Kyllä". Angina pectoriksen kohdalla sen sijaan "En tiedä" on yleensä "Ei". Helppo ratkaisu voisi olla muuttaa vastausvaihtoehdon nimi muotoon "Ei/En tiedä". Näin ei tarvittaisi uusia logiikoita tai muutoksia palautteisiin.

**Comment by kainutom** [comment]
"Esim. ikäkenttään tulisi pystyä syöttämään ainoastaan positiivinen kokonaisluku väliltä 0-120, painoon positiivinen rationaaliluku väliltä 30-200 ja pituuteen 140-250 jne. Skriptilogiikka ei toimi, jos kenttä palauttaa string-arvon." Tämä pitäisi ratkaista niin että lomakkeen kysymyksessä ilmaistaan sallittu arvoväli. Lisäksi lomakkeessa pitäisi pystyä ilmoittamaan onko kyseessä desimaali- vai kokonaisluku. Stringejä ei numerokentissä pysty käsittääkseni syöttämään.

**Comment by kainutom** [comment]
Nuo tässä issuessa listatut asiat minun puolesta ok @jarinumminen

**Comment by jarinumminen** [comment]
suljetaan
