### ISSUE TITLE
Terveystarkastus 153: palauterajapinta heittää poikkeuksen

### ISSUE THREAD

**Issue by kainutom** [omahoito/rfc#99]
Unknown error: TypeError: Cannot read property '0' of undefined

[Terveystarkastus_153_filled_teksti .txt](https://github.com/omahoito/rfc/files/1274547/Terveystarkastus_153_filled_teksti.txt)

**Comment by kainutom** [comment]
Ikä on näköjään pyynnössä 0 arvona, tutkin onko muitakin.

**Comment by kainutom** [comment]
Sama poikkeus vaikka iäksi asettaa esim. 40

**Comment by vlindhol** [comment]
Vika on paikannettu moottorin, se palauttaa jotain roskaa eikä anna muistutteita vaikka pitäisi.

**Comment by kainutom** [comment]
Tämä toimii nyt ok. Palautteet tulee läpi @jarinumminen

**Comment by jarinumminen** [comment]
suljetaan
